name: Release

on:
  push:
    tags:
      - "*/*" # Matches 'pkgname/v1.2.3'

permissions:
  contents: write

jobs:
  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract package info
        id: package_info
        run: |
          PACKAGE_NAME=$(jq -r .name package.json)
          VERSION=$(jq -r .version package.json)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Extract changelog section
        run: |
          awk "/## \\[${VERSION}\\]/,/## \\[/" CHANGELOG.md | sed '$d' > release-notes.md || echo "No changelog entry found" > release-notes.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ env.VERSION }}
          body_path: release-notes.md
          draft: false
          prerelease: ${{ contains(env.VERSION, 'beta') || contains(env.VERSION, 'rc') }}
          files: |
            dist/*.tgz
